# Generated by Django 4.0.1 on 2022-01-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='names',
            options={'managed': False},
        ),
    ]
