# Generated by Django 4.0.1 on 2022-01-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0002_alter_names_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='names',
            options={},
        ),
    ]
